sudo: required # Sudo required tells Travis that we need superuser permissions to run this build
language: generic

services:
  - docker # Tells Travis to install docker

before_install: # Series of command before the build is run
  - docker build -t trentgillis/docker-react -f Dockerfile.dev .

script: # Series of commands to run as part of the build
  - docker run -e CI=true trentgillis/docker-react npm run test -- --coverage # Runs the tests for our React applications

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: elasticbeanstalk-us-west-2-425677955837 # When Travis deploys our files, it'll zip all of our files up and put them in an S3 bucket which is essentially a hard drive on AWS. This is found under the S3 service on AWS
  bucket_path: "docker-react" # Path to this apps directory inside of the S3 instance being used by elasticbeanstalk
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
